
services:
    jenkins:
        image: patrickmoussi/jenkins:lts
        container_name: jenkins
        user: root
        ports:
            - 8090:8080
            - 50000:50000
        volumes:
            - ./jenkins_configurations:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock 
